version: "3.9"

services:
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - ./dump.sql:/dump.sql
      - pq-data:/var/lib/postgresql/data
    ports:
      - "5440:5439"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8001"

  pgadmin:
    image: dpage/pgadmin4:6.11
    ports:
      - 8081:81
    volumes:
      - pgadmin3:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

volumes:
  pq-data:
  pgadmin3:
